services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8088:80/tcp"
    env_file:
      - .env
    environment:
      - FTLCONF_webserver_api_password=${FTLCONF_WEBSERVER_API_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./pihole/etc/pihole:/etc/pihole
      - ./pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
