services:
  otbr:
    image: ghcr.io/ownbee/hass-otbr-docker
    container_name: otbr
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - DEVICE=/dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_484fc339f411f011b33f0714773d9da9-if00-port0
      - BAUDRATE=460800
      - BACKBONE_IF=enp2s0
      - OTBR_REST_PORT=8081
      - OTBR_WEB_PORT=8084
      - OTBR_LOG_LEVEL=info 
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_484fc339f411f011b33f0714773d9da9-if00-port0:/dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_484fc339f411f011b33f0714773d9da9-if00-port0
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /var/lib/otbr:/data

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./matter-server/data:/data
      - /run/dbus:/run/dbus:ro
