services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./data:/root/.ollama
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true

